package uk.co.quidos.gdsap.framework.charge.persistence;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import uk.co.quidos.dal.BaseMapper;
import uk.co.quidos.gdsap.framework.charge.persistence.object.GdsapChargeCreditPrice;

public interface GdsapChargeCreditPriceMapper extends BaseMapper<GdsapChargeCreditPrice, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsap_charge_credit_price
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsap_charge_credit_price
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    int insertSelective(GdsapChargeCreditPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsap_charge_credit_price
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    GdsapChargeCreditPrice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsap_charge_credit_price
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    int updateByPrimaryKeySelective(GdsapChargeCreditPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsap_charge_credit_price
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    int updateByPrimaryKey(GdsapChargeCreditPrice record);
    
    /**
     * 根据creditType获取GdsapChargeCreditPrice集合，按minNum降序排列
     * @param creditType
     * @return
     */
    List<GdsapChargeCreditPrice> selectByType(Integer creditType);
    
    GdsapChargeCreditPrice selectByType_MinNum(@Param("creditType") Integer creditType, @Param("minNum") Integer minNum);
}