package uk.co.quidos.gdsap.framework.charge.persistence;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import uk.co.quidos.gdsap.framework.charge.persistence.object.GdsapChargeUserBalance;

@Repository
public interface GdsapChargeUserBalanceMapper {
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsap_charge_user_balance
     *
     * @mbggenerated Fri Oct 31 16:08:33 CST 2014
     */
    int deleteByPrimaryKey(GdsapChargeUserBalance key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsap_charge_user_balance
     *
     * @mbggenerated Fri Oct 31 16:08:33 CST 2014
     */
    int insert(GdsapChargeUserBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsap_charge_user_balance
     *
     * @mbggenerated Fri Oct 31 16:08:33 CST 2014
     */
    int insertSelective(GdsapChargeUserBalance record);
    
    GdsapChargeUserBalance load(@Param("userId") Long userId, @Param("balanceType") Integer balanceType);

    void updateBalance(GdsapChargeUserBalance record);
    
}