package uk.co.quidos.gdsap.framework.charge.persistence.object;

import uk.co.quidos.dal.object.AbstractDO;

public class GdsapChargeCreditPrice  extends AbstractDO {
   
	private static final long serialVersionUID = 3174389736467072235L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gdsap_charge_credit_price.ID
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gdsap_charge_credit_price.MIN_NUM
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    private Integer minNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gdsap_charge_credit_price.PRICE
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gdsap_charge_credit_price.CREDIT_TYPE
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    private Integer creditType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gdsap_charge_credit_price.QUIDOS_VAT
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    private Double quidosVat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gdsap_charge_credit_price.REGISTER_FEE
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    private Double registerFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gdsap_charge_credit_price.REGISTER_VAT
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    private Double registerVat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gdsap_charge_credit_price.ID
     *
     * @return the value of gdsap_charge_credit_price.ID
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gdsap_charge_credit_price.ID
     *
     * @param id the value for gdsap_charge_credit_price.ID
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gdsap_charge_credit_price.MIN_NUM
     *
     * @return the value of gdsap_charge_credit_price.MIN_NUM
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    public Integer getMinNum() {
        return minNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gdsap_charge_credit_price.MIN_NUM
     *
     * @param minNum the value for gdsap_charge_credit_price.MIN_NUM
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    public void setMinNum(Integer minNum) {
        this.minNum = minNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gdsap_charge_credit_price.PRICE
     *
     * @return the value of gdsap_charge_credit_price.PRICE
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gdsap_charge_credit_price.PRICE
     *
     * @param price the value for gdsap_charge_credit_price.PRICE
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gdsap_charge_credit_price.CREDIT_TYPE
     *
     * @return the value of gdsap_charge_credit_price.CREDIT_TYPE
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    public Integer getCreditType() {
        return creditType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gdsap_charge_credit_price.CREDIT_TYPE
     *
     * @param creditType the value for gdsap_charge_credit_price.CREDIT_TYPE
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    public void setCreditType(Integer creditType) {
        this.creditType = creditType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gdsap_charge_credit_price.QUIDOS_VAT
     *
     * @return the value of gdsap_charge_credit_price.QUIDOS_VAT
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    public Double getQuidosVat() {
        return quidosVat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gdsap_charge_credit_price.QUIDOS_VAT
     *
     * @param quidosVat the value for gdsap_charge_credit_price.QUIDOS_VAT
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    public void setQuidosVat(Double quidosVat) {
        this.quidosVat = quidosVat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gdsap_charge_credit_price.REGISTER_FEE
     *
     * @return the value of gdsap_charge_credit_price.REGISTER_FEE
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    public Double getRegisterFee() {
        return registerFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gdsap_charge_credit_price.REGISTER_FEE
     *
     * @param registerFee the value for gdsap_charge_credit_price.REGISTER_FEE
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    public void setRegisterFee(Double registerFee) {
        this.registerFee = registerFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gdsap_charge_credit_price.REGISTER_VAT
     *
     * @return the value of gdsap_charge_credit_price.REGISTER_VAT
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    public Double getRegisterVat() {
        return registerVat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gdsap_charge_credit_price.REGISTER_VAT
     *
     * @param registerVat the value for gdsap_charge_credit_price.REGISTER_VAT
     *
     * @mbggenerated Sun Nov 02 17:01:05 CST 2014
     */
    public void setRegisterVat(Double registerVat) {
        this.registerVat = registerVat;
    }
}