package uk.co.quidos.gdsap.framework.charge.persistence.object;

import java.util.Date;

import uk.co.quidos.dal.object.AbstractDO;

public class GdsapChargeTransactionRecord extends AbstractDO {

	private static final long serialVersionUID = -8404061717322266905L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gdsap_charge_transaction_record.ID
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gdsap_charge_transaction_record.TRANSACTION_NUM
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    private Double transactionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gdsap_charge_transaction_record.TRANSACTION_TYPE
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    private Integer transactionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gdsap_charge_transaction_record.RECORD_TYPE
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    private Integer recordType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gdsap_charge_transaction_record.PURPOSE
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    private Integer purpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gdsap_charge_transaction_record.USER_ID
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gdsap_charge_transaction_record.USER_NAME
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gdsap_charge_transaction_record.ADMIN_ID
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gdsap_charge_transaction_record.ADMIN_USER_NAME
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    private String adminUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gdsap_charge_transaction_record.REPORT_ID
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    private Long reportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gdsap_charge_transaction_record.INSERT_TIME
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    private Date insertTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gdsap_charge_transaction_record.ID
     *
     * @return the value of gdsap_charge_transaction_record.ID
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gdsap_charge_transaction_record.ID
     *
     * @param id the value for gdsap_charge_transaction_record.ID
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gdsap_charge_transaction_record.TRANSACTION_NUM
     *
     * @return the value of gdsap_charge_transaction_record.TRANSACTION_NUM
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public Double getTransactionNum() {
        return transactionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gdsap_charge_transaction_record.TRANSACTION_NUM
     *
     * @param transactionNum the value for gdsap_charge_transaction_record.TRANSACTION_NUM
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public void setTransactionNum(Double transactionNum) {
        this.transactionNum = transactionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gdsap_charge_transaction_record.TRANSACTION_TYPE
     *
     * @return the value of gdsap_charge_transaction_record.TRANSACTION_TYPE
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public Integer getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gdsap_charge_transaction_record.TRANSACTION_TYPE
     *
     * @param transactionType the value for gdsap_charge_transaction_record.TRANSACTION_TYPE
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public void setTransactionType(Integer transactionType) {
        this.transactionType = transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gdsap_charge_transaction_record.RECORD_TYPE
     *
     * @return the value of gdsap_charge_transaction_record.RECORD_TYPE
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public Integer getRecordType() {
        return recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gdsap_charge_transaction_record.RECORD_TYPE
     *
     * @param recordType the value for gdsap_charge_transaction_record.RECORD_TYPE
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public void setRecordType(Integer recordType) {
        this.recordType = recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gdsap_charge_transaction_record.PURPOSE
     *
     * @return the value of gdsap_charge_transaction_record.PURPOSE
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public Integer getPurpose() {
        return purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gdsap_charge_transaction_record.PURPOSE
     *
     * @param purpose the value for gdsap_charge_transaction_record.PURPOSE
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public void setPurpose(Integer purpose) {
        this.purpose = purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gdsap_charge_transaction_record.USER_ID
     *
     * @return the value of gdsap_charge_transaction_record.USER_ID
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gdsap_charge_transaction_record.USER_ID
     *
     * @param userId the value for gdsap_charge_transaction_record.USER_ID
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gdsap_charge_transaction_record.USER_NAME
     *
     * @return the value of gdsap_charge_transaction_record.USER_NAME
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gdsap_charge_transaction_record.USER_NAME
     *
     * @param userName the value for gdsap_charge_transaction_record.USER_NAME
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gdsap_charge_transaction_record.ADMIN_ID
     *
     * @return the value of gdsap_charge_transaction_record.ADMIN_ID
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gdsap_charge_transaction_record.ADMIN_ID
     *
     * @param adminId the value for gdsap_charge_transaction_record.ADMIN_ID
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gdsap_charge_transaction_record.ADMIN_USER_NAME
     *
     * @return the value of gdsap_charge_transaction_record.ADMIN_USER_NAME
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public String getAdminUserName() {
        return adminUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gdsap_charge_transaction_record.ADMIN_USER_NAME
     *
     * @param adminUserName the value for gdsap_charge_transaction_record.ADMIN_USER_NAME
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public void setAdminUserName(String adminUserName) {
        this.adminUserName = adminUserName == null ? null : adminUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gdsap_charge_transaction_record.REPORT_ID
     *
     * @return the value of gdsap_charge_transaction_record.REPORT_ID
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public Long getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gdsap_charge_transaction_record.REPORT_ID
     *
     * @param reportId the value for gdsap_charge_transaction_record.REPORT_ID
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gdsap_charge_transaction_record.INSERT_TIME
     *
     * @return the value of gdsap_charge_transaction_record.INSERT_TIME
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gdsap_charge_transaction_record.INSERT_TIME
     *
     * @param insertTime the value for gdsap_charge_transaction_record.INSERT_TIME
     *
     * @mbggenerated Fri Oct 31 17:19:10 CST 2014
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }
}