package uk.co.quidos.gdsap.framework.charge.persistence.object;

import uk.co.quidos.dal.object.AbstractDO;


public class GdsapChargeUserBalance extends AbstractDO {
 
	private static final long serialVersionUID = 2577523126006300187L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gdsap_charge_user_balance.USER_ID
     *
     * @mbggenerated Fri Oct 31 16:08:33 CST 2014
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gdsap_charge_user_balance.BALANCE_TYPE
     *
     * @mbggenerated Fri Oct 31 16:08:33 CST 2014
     */
    private Integer balanceType;
    
    private Double balance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gdsap_charge_user_balance.USER_ID
     *
     * @return the value of gdsap_charge_user_balance.USER_ID
     *
     * @mbggenerated Fri Oct 31 16:08:33 CST 2014
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gdsap_charge_user_balance.USER_ID
     *
     * @param userId the value for gdsap_charge_user_balance.USER_ID
     *
     * @mbggenerated Fri Oct 31 16:08:33 CST 2014
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gdsap_charge_user_balance.BALANCE_TYPE
     *
     * @return the value of gdsap_charge_user_balance.BALANCE_TYPE
     *
     * @mbggenerated Fri Oct 31 16:08:33 CST 2014
     */
    public Integer getBalanceType() {
        return balanceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gdsap_charge_user_balance.BALANCE_TYPE
     *
     * @param balanceType the value for gdsap_charge_user_balance.BALANCE_TYPE
     *
     * @mbggenerated Fri Oct 31 16:08:33 CST 2014
     */
    public void setBalanceType(Integer balanceType) {
        this.balanceType = balanceType;
    }

	public Double getBalance() {
		return balance;
	}

	public void setBalance(Double balance) {
		this.balance = balance;
	}
}